### 관리자 상품 등록
POST {{commerce-api}}/api-admin/v1/coupons
X-Loopers-Ldap: admin
Content-Type: application/json

{
  "name": "신규가입 10% 할인",
  "type": "RATE",
  "value": 10,
  "minOrderAmount": 10000,
  "expiredAt": "2026-12-31T23:59:59+09:00"
}
