### 회원가입
POST {{commerce-api}}/api/v1/members/register
Content-Type: application/json

{
  "loginId": "user01",
  "password": "Password1!",
  "name": "홍길동",
  "birthDate": "19900628",
  "email": "test@test.com"
}

### 내 정보 조회
GET {{commerce-api}}/api/v1/members/me
X-Loopers-LoginId: user01
X-Loopers-LoginPw: Password1!

### 비밀번호 수정
PATCH {{commerce-api}}/api/v1/members/password
Content-Type: application/json
X-Loopers-LoginId: user01
X-Loopers-LoginPw: Password1!

{
  "newPassword": "NewPass1!"
}
