### 회원가입
POST {{commerce-api}}/api/v1/members
Content-Type: application/json

{
  "loginId": "loopers123",
  "password": "Loopers123!",
  "name": "gunyoung",
  "birthDate": "1995-05-20",
  "email": "loopers@gmail.com"
}

### 내 정보 조회
GET {{commerce-api}}/api/v1/members/me
X-Loopers-LoginId: loopers123
X-Loopers-LoginPw: Loopers123!

### 비밀번호 수정
PATCH {{commerce-api}}/api/v1/members/me/password
Content-Type: application/json
X-Loopers-LoginId: loopers123
X-Loopers-LoginPw: Loopers123!

{
  "newPassword": "NewLoopers1!"
}
