### 주문 생성 - 쿠폰 미적용
POST {{commerce-api}}/api/v1/orders
X-Loopers-LoginId: loopers123
X-Loopers-LoginPw: Loopers123!
Content-Type: application/json

{
  "items": [
    {
      "productId": 1,
      "quantity": 2
    },
    {
      "productId": 3,
      "quantity": 1
    }
  ]
}

### 주문 생성 - 쿠폰 적용
POST {{commerce-api}}/api/v1/orders
X-Loopers-LoginId: loopers123
X-Loopers-LoginPw: Loopers123!
Content-Type: application/json

{
  "items": [
    {
      "productId": 1,
      "quantity": 2
    }
  ],
  "couponId": 1
}

### 내 주문 목록 조회
GET {{commerce-api}}/api/v1/orders?startAt=2026-01-01&endAt=2026-12-31
X-Loopers-LoginId: loopers123
X-Loopers-LoginPw: Loopers123!

### 내 주문 상세 조회
GET {{commerce-api}}/api/v1/orders/1
X-Loopers-LoginId: loopers123
X-Loopers-LoginPw: Loopers123!
