### 회원가입
POST {{commerce-api}}/api/v1/users
Content-Type: application/json

{
  "loginId": "testUser01",
  "password": "Pass!234",
  "name": "홍길동",
  "birthDate": "19900101",
  "email": "test@example.com"
}

### 내 정보 조회
GET {{commerce-api}}/api/v1/users/me
X-Loopers-LoginId: testUser01
X-Loopers-LoginPw: Pass!234

### 비밀번호 변경
PATCH {{commerce-api}}/api/v1/users/me/password
Content-Type: application/json
X-Loopers-LoginId: testUser01
X-Loopers-LoginPw: Pass!234

{
  "currentPassword": "Pass!234",
  "newPassword": "NewPass!9"
}
