server:
  shutdown: graceful
  port: 8083

spring:
  main:
    web-application-type: servlet
  application:
    name: commerce-streamer
  profiles:
    active: local
  config:
    import:
      - jpa.yml
      - redis.yml
      - kafka.yml
      - logging.yml
      - monitoring.yml
  kafka:
    consumer:
      group-id: commerce-streamer
      auto-offset-reset: latest
      enable-auto-commit: false
    producer:
      acks: all
      properties:
        enable.idempotence: true

---
spring:
  config:
    activate:
      on-profile: local, test

---
spring:
  config:
    activate:
      on-profile: dev

---
spring:
  config:
    activate:
      on-profile: qa

---
spring:
  config:
    activate:
      on-profile: prd
