spring:
  main:
    web-application-type: none
  application:
    name: commerce-batch
  profiles:
    active: local
  config:
    import:
      - jpa.yml
      - redis.yml
      - logging.yml
      - monitoring.yml
  batch:
    job:
      name: ${job.name:}
    jdbc:
      initialize-schema: never

management:
  health:
    defaults:
      enabled: false

waiting-queue:
  orders:
    enabled: true
    consume-delay: 100ms
    admit-count: 5
    allowed-ttl: 60s
    heartbeat-ttl: 10s

---
spring:
  config:
    activate:
      on-profile: local, test
  batch:
    jdbc:
      initialize-schema: always

waiting-queue:
  orders:
    enabled: false

---
spring:
  config:
    activate:
      on-profile: dev

---
spring:
  config:
    activate:
      on-profile: qa

---
spring:
  config:
    activate:
      on-profile: prd

springdoc:
  api-docs:
    enabled: false
