server:
  shutdown: graceful
  tomcat:
    threads:
      max: 200 # 최대 워커 스레드 수 (default : 200)
      min-spare: 10 # 최소 유지 스레드 수 (default : 10)
    connection-timeout: 1m # 연결 타임아웃 (ms) (default : 60000ms = 1m)
    max-connections: 8192 # 최대 동시 연결 수 (default : 8192)
    accept-count: 100 # 대기 큐 크기 (default : 100)
    keep-alive-timeout: 60s # 60s
  max-http-request-header-size: 8KB

spring:
  main:
    web-application-type: servlet
  application:
    name: commerce-api
  profiles:
    active: local
  config:
    import:
      - jpa.yml
      - redis.yml
      - kafka.yml
      - logging.yml
      - monitoring.yml

event-coupon:
  kafka:
    topic-name: commerce.coupon-publish-requested.v1

springdoc:
  use-fqn: true
  swagger-ui:
    path: /swagger-ui.html
    persist-authorization: true

pg-simulator:
  base-url: http://localhost:8082
  callback-url: http://localhost:8080/api/v1/payments/callback
  timeout: 10s
  retry:
    max-retries: 3
    wait-duration: 100ms
    randomization-factor: 0.5
  circuit-breaker:
    failure-rate-threshold: 10
    sliding-window-size: 50
    minimum-number-of-calls: 10
    wait-duration-in-open-state: 10s
    permitted-number-of-calls-in-half-open-state: 2

waiting-queue:
  orders:
    enabled: true
    traffic-threshold-per-second: 100
    token-ttl: 30m
    allowed-ttl: 60s
    heartbeat-ttl: 10s
    admit-rate-per-second: 50

---
spring:
  config:
    activate:
      on-profile: local, test
  kafka:
    listener:
      auto-startup: false

waiting-queue:
  orders:
    enabled: false

---
spring:
  config:
    activate:
      on-profile: dev

---
spring:
  config:
    activate:
      on-profile: qa

---
spring:
  config:
    activate:
      on-profile: prd

springdoc:
  api-docs:
    enabled: false
